cart_app/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,
         name='cart_remove'),
]

orders/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create_order/', views.order_create, name='order_create'),

]

shop_garden/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.views.i18n import set_language
from django.contrib.sitemaps.views import sitemap
from shop_main_app.sitemap import CategorySitemap, ProductSitemap, StaticSitemap

sitemaps = {
    'static_pages': StaticSitemap,
    'categories': CategorySitemap,
    'products': ProductSitemap,
}

urlpatterns = [
    path('i18n/', set_language, name='set_language'),
    path('admin/', admin.site.urls),
    path('', include('shop_main_app.urls')),
    path('', include('options_app.urls')),
    path('', include('orders.urls')),
    path('cart/', include('cart_app.urls', namespace='cart')),
    path('tinymce/', include('tinymce.urls')),
    path('sitemap.xml', sitemap,
         {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('robots.txt', TemplateView.as_view(template_name='robots/robots.txt',
                                                            content_type='text/plain'))
                    ]
else:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'shop_main_app.views.handler404'
handler500 = 'shop_main_app.views.handler500'

templates/cart_details.html
{% extends "index.html" %}
{% load static %}

{% block custom_title %}
    <title>Кошик</title>
{% endblock %}

{% block custom_meta %}
    <meta name="description" content="Кошик">
    <meta name="robots" content="noindex, nofollow">
{% endblock %}

{% block content %}
    <div class="container py-5 h-100 mb-3">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col">
                <div class="card">
                    <div class="card-body p-4">
                        <div class="row">
                            <div class="col-lg-7">
                                <h5 class="mb-3"><a href="{% url 'main' %}" class="text-body"><i
                                        class="fas fa-long-arrow-alt-left me-2"></i></a>Повернутись до покупок</h5>
                                <hr>
                                <div class="d-flex justify-content-between align-items-center mb-4">
                                    <div>
                                        <p class="mb-1">Ваш кошик</p>
                                        <p class="mb-0">Ви маєте {{ cart|length }} товари </p>
                                    </div>
                                </div>
                                <div id="product-container">
                                    {% for item in cart %}
                                        {% with product=item.product %}
                                            <div class="card" style="margin-bottom: 15px" id="cart">
                                                <div class="card-body">
                                                    <div class="d-flex justify-content-between">
                                                        <div class="d-flex flex-row align-items-center">
                                                            <div>
                                                                <img src="{% if product.images.all.0.image %}
                                                                            {{ product.images.all.0.image.url }}
                                                                            {% else %}
                                                                            {% static 'not_available_icons/no-image-icon-23485.png' %}
                                                                            {% endif %}"
                                                                     class="img-fluid rounded-3" alt="Shopping item"
                                                                     style="width: 65px;">
                                                            </div>
                                                            <div class="ms-3">
                                                                <h5>{{ product.title }}</h5>
                                                                <p class="small mb-0">Категорія:
                                                                    {% for category in  product.category.all %}
                                                                        {{ category.name }}
                                                                    {% endfor %}
                                                                </p>
                                                            </div>
                                                        </div>
                                                        <div class="d-flex flex-row align-items-center">
                                                            <a type="button" class="btn btn-primary rounded-pill me-2"
                                                               data-bs-toggle="modal"
                                                               data-bs-target="#staticBackdrop{{ product.id }}">
                                                                {{ item.quantity }} {{ product.measure.name }}
                                                            </a>


                                                            <!-- Modal -->
                                                            <div class="modal fade" id="staticBackdrop{{ product.id }}"
                                                                 data-bs-backdrop="static" data-bs-keyboard="false"
                                                                 tabindex="-1"
                                                                 aria-labelledby="staticBackdrop{{ product.id }}Label"
                                                                 aria-hidden="true">
                                                                <div class="modal-dialog">
                                                                    <div class="modal-content">
                                                                        <div class="modal-header">
                                                                            <h5 class="modal-title"
                                                                                id="staticBackdrop{{ product.id }}Label">
                                                                                Змінити кількість</h5>
                                                                            <button type="button" class="btn-close"
                                                                                    data-bs-dismiss="modal"
                                                                                    aria-label="Close"></button>
                                                                        </div>
                                                                        <form action="{% url "cart:cart_add" product.id %}"
                                                                              method="post">
                                                                            <div class="modal-body">
                                                                                <div style="width: 50px;">
                                                                                    {% csrf_token %}
                                                                                    {{ item.update_quantity_form.quantity }}
                                                                                    {{ item.update_quantity_form.override }}
                                                                                </div>
                                                                            </div>
                                                                            <div class="modal-footer">
                                                                                <button type="submit"
                                                                                        class="btn btn-primary"
                                                                                        value="Update">Оновити
                                                                                </button>
                                                                            </div>
                                                                        </form>
                                                                    </div>
                                                                </div>
                                                            </div>

                                                            <div class="font-weight-bold">
                                                                <h5 class="mb-0 ms-2 me-2">{{ item.price }} ₴</h5>
                                                            </div>
                                                            <form id="deleteForm"
                                                                  action="{% url "cart:cart_remove" product.id %}"
                                                                  method="post">

                                                                {% csrf_token %}
                                                                <button type="submit" id="deleteButton"
                                                                        class="btn  btn-secondary ms-2">
                                                                    <i class="fas fa-trash-alt"></i>
                                                                </button>
                                                            </form>

                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        {% endwith %}
                                    {% endfor %}
                                </div>
                                <div id="total_price">
                                    <p>Загальна вартість: {{ total_price }} ₴</p>
                                </div>
                            </div>
                            <div class="col-lg-5">
                                <div class="card   rounded-3">
                                    <div class="card-body">
                                        <h5 class="card-title mb-3">Оформити замовлення</h5>
                                        <form method="post" action="{% url 'order_create' %}">
                                            <div class="row">
                                                <div class="mb-3">
                                                    <p class="mb-0">Ім'я</p>
                                                    <div class="form-outline">
                                                        {{ order_form.first_name }}
                                                    </div>
                                                </div>

                                                <div class="mb-3">
                                                    <p class="mb-0">Прізвище</p>
                                                    <div class="form-outline">
                                                        {{ order_form.last_name }}
                                                    </div>
                                                </div>

                                                <div class=" mb-3">
                                                    <p class="mb-0">Електронна пошта</p>
                                                    <div class="form-outline">
                                                        {{ order_form.email }}
                                                    </div>
                                                </div>

                                                <div class=" col-6 mb-3">
                                                    <p class="mb-0">Телефон</p>
                                                    <div class="form-outline">
                                                        {{ order_form.phone }}
                                                    </div>
                                                </div>

                                                <div class=" col-6 mb-3">
                                                    <p class="mb-0">Населений пункт</p>
                                                    <div class="form-outline">
{#                                                        <input type="text" id="cityInput" name="cityInput">#}
                                                        {{ order_form.city }}
                                                        <select class="form-select" id="citySelect" name="citySelect"
                                                                style="display: none;"
                                                                aria-label="Default select example">

                                                        </select>

                                                    </div>
                                                </div>

                                                <div class=" col-6 mb-3">
                                                    <p class="mb-0">Адеса відділення Нової Пошти</p>
                                                    <div class="form-outline">
                                                        {{ order_form.warehouse }}

                                                        <select class="form-select" disabled id="warehouse" name="warehouse">

                                                        </select>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="float-end">
                                                {% csrf_token %}
                                                <button type="submit" class="btn btn-success shadow-0 border">
                                                    Оформити
                                                </button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>

                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="{% static 'js/nova_post_handler.js' %}"></script>
    <script>
        const staticJsonFilePath = "{% static "jsons/nova_post_fullinfo.json" %}";
    </script>

{% endblock %}

{% block custom_scripts %}
    <script src="{% static 'js/cart-styles.js' %}"></script>
{% endblock %}

templates/category_details.html
{% extends 'index.html' %}
{% load url_transform %}
{% load static %}
{% load custom_length %}

{% block custom_title %}
    {% for category in category_list %}
        {% if category.slug == slug %}
            <title>{{ category.meta_title }}</title>
            <meta name="description" content="{{ category.meta_description }}">
        {% endif %}
    {% endfor %}
{% endblock %}

{% block custom_meta %}
    <meta name="robots" content="index, follow">
{% endblock %}

{% block content %}
    <section class="row" style="margin-top: 25px">
        <aside class="col-lg-3 col-md-5" style="margin-bottom: 15px;">
            <ul class="list-group" id="category-list">
                <li class="list-group-item list-group-item-action active">Категорії</li>
                {% for category in category_list %}
                    <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-start"
                        style="text-align: left">
                        <div style="display: flex; justify-content: space-between;">
                            <a href="{% url 'category_list' category.slug %}">
                                <img style="width: 30px; height: 30px;"
                                     src="{{ category.image.url }}" alt="category_{{ category.slug }}">
                                <a href="{% url 'category_list' category.slug %}"
                                   style="margin-bottom: 0; font-size: 20px; margin-left: 25px;">{{ category.name }}</a>
                            </a>
                        </div>
                        <div>
                            <span class="badge bg-primary rounded-pill">{{ category.products.all|custom_length }} </span>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </aside>
        <section class="col-lg-9 col-md-7">
            <div style="margin-bottom: 15px">
                {% for category in category_list %}
                    {% if category.slug == slug %}
                        <header>
                            <h1 class="d-md-block shadow p-3 mb-5 bg-body-tertiary rounded">{{ category.name }}</h1>
                        </header>
                    {% endif %}
                {% endfor %}
                {% if object_list|length > 1 %}
                    <div style="display: flex;">
                        <form style="display: flex; justify-content: space-between; width: 100%" class="filters_form">
                            <div>
                                <div class="wrapper">
                                    <div class="price-input">
                                        <div class="field">
                                            {#                                        <span>З</span>#}
                                            <label>
                                                <input type="number" value="{{ min_filter_value }}" class="min-input"/>
                                            </label>
                                        </div>
                                        <div class="seperator">—</div>
                                        <div class="field">
                                            {#                                        <span>По</span>#}
                                            <label>
                                                <input type="number" value="{{ max_filter_value }}" class="max-input"/>
                                            </label>
                                        </div>
                                    </div>
                                    <div class="slider">
                                        <div class="progress"></div>
                                    </div>
                                    <div class="range-input">
                                        <input
                                                name="min"
                                                type="range"
                                                min="{{ min_range_value }}"
                                                max="{{ max_range_value }}"
                                                value="{{ min_filter_value }}"
                                                class="min-range"
                                        />
                                        <input
                                                type="range"
                                                min="{{ min_range_value }}"
                                                max="{{ max_range_value }}"
                                                value="{{ max_filter_value }}"
                                                class="max-range"
                                                name="max"
                                        />
                                    </div>
                                </div>
                            </div>
                            <div style="" class="sort">
                                <select class="form-select" aria-label="Default select example" name='sort'>
                                    <option value="price">С початку дешеві</option>
                                    <option selected value="-price">С початку дорожчі</option>
                                </select>
                                <div class="mt-3">
                                    <label for="discount">Тільки товари зі знижкою</label>
                                    <input type="checkbox" id="discount" name="discount"/>
                                </div>

                                <button class="btn btn-outline-success" type="submit" style="margin-top: 15px">Виконати
                                </button>
                            </div>
                        </form>
                    </div>
                {% endif %}
            </div>
            {% if object_list %}
                <div class="container">
                <div class="row">
                    {% for product in object_list %}
                        {% if product.index %}
                            <div class="col-lg-3 col-md-6 mb-4">
                                <div class="card">
                                    <div class="bg-image hover-zoom ripple ripple-surface ripple-surface-light"
                                         data-mdb-ripple-color="light">
                                        {% if product.images.all.0.image.url %}
                                            <img src="{{ product.images.all.0.image.url }}"
                                                 alt="{{ product.slug }}"
                                                    {% if not product.availability %}
                                                 style="filter: grayscale(1)"
                                                    {% endif %}
                                                 class="w-100"/>
                                        {% else %}
                                            <img src="{% static 'not_available_icons/no-image-icon-23485.png' %}"
                                                 class="w-100" alt="not_available"
                                            >
                                        {% endif %}
                                        <a href="{% url 'product_details' product.slug %}">
                                            <div class="mask">
                                                <div class="d-flex justify-content-start align-items-end h-100">
                                                    <h5>
                                                        {% if product.is_it_new_product %}
                                                            <span class="badge bg-success ms-2">Новинка</span>
                                                        {% endif %}
                                                        {% if product.get_price_with_discount != product.price %}
                                                            <span class="badge bg-danger ms-2">{{ product.discount }}%</span>
                                                        {% endif %}
                                                    </h5>
                                                </div>
                                            </div>
                                            <div class="hover-overlay">
                                                <div class="mask"
                                                     style="background-color: rgba(251, 251, 251, 0.15);"></div>
                                            </div>
                                        </a>
                                    </div>
                                    <div class="card-body">
                                        <a href="{% url 'product_details' product.slug %}" class="text-reset">
                                            <h5 class="card-title mb-3">{{ product.title }}</h5>
                                        </a>
                                        {% if product.get_price_with_discount != product.price %}
                                            <h6 class="mb-3">
                                                {{ product.get_price_with_discount }} ₴<s>
                                                <strong
                                                        class="ms-2 text-danger">{{ product.price }} ₴</strong>
                                            </s>
                                            </h6>
                                        {% else %}
                                            <h6 class="mb-3">{{ product.price }} ₴</h6>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
                <div>
            {% else %}
                <div class="container">
                    <div class="alert alert-danger" role="alert">
                        <h4 class="alert-heading">Упс... Нажаль ця категорія порожня(((</h4>
                        <hr>
                    </div>
                </div>
            {% endif %}
            <div aria-label="..." style="display: flex; justify-content: center" class="mb-3">
                <ul class="pagination d-flex">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                        <a class="page-link"
                           href="?{% query_transform page=page_obj.previous_page_number %}">Попередня</a>
                    {% endif %}
                    </li>
                    {% for p in paginator.page_range %}
                        <li class="page-item">
                            <a class="page-link" href="?{% query_transform page=p %}">{{ p }}</a>
                        </li>
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link"
                               href="?{% query_transform page=page_obj.next_page_number %}">Наступна</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
            </div>
        </section>
    </section>
    <article>
        {% for category in category_list %}
            {% if category.slug == slug %}
                {{ category.description|safe }}
            {% endif %}
        {% endfor %}
    </article>
{% endblock %}

{% block custom_scripts %}
    <script src="{% static 'js/app.js' %}"></script>
    {#    <script src="{% static 'js/card-styles.js' %}"></script>#}
    <script src="{% static 'js/filter-saver.js' %}"></script>
{% endblock %}

templates/contact_page.html
{% extends 'index.html' %}

{% block custom_title %}
    <title>{{ about_info.meta_title }}</title>
{% endblock %}

{% block custom_meta %}
    <meta name="description" content="{{ about_info.meta_description }}">
    <meta name="robots" content="index, follow">
{% endblock %}

{% block content %}

    <section class="container page">
        <div class="row">
            <article class="col col-12 col-lg-5">
                {{ about_info.left_side_of_page|safe }}
            </article>
            <article class="col col-12 offset-lg-1 col-lg-6 mt-5 mt-lg-0">
                {{ about_info.right_side_of_page|safe }}
            </article>
        </div>
        <h3>Маєте питання? Звертайтеся за цією формою:</h3>
        <section style="width: 100%; display: flex; justify-content: center; margin-top: 20px; margin-bottom: 20px">
            <form style="width: 40rem;" method="post" action="{% url 'contact-form-create' %}">
                {% csrf_token %}

                {% if question_form.non_field_errors %}
                    <ul>
                        {% for error in question_form.non_field_errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
                <!-- Name input -->
                <div data-mdb-input-init class="form-outline mb-4">
                    {{ question_form.name }}
                    <label class="form-label" for="name">Ім'я</label>
                    {{ question_form.name.errors }}
                </div>

                <!-- Email input -->
                <div data-mdb-input-init class="form-outline mb-4">
                    {{ question_form.email }}
                    <label class="form-label" for="email">Електронна адреса</label>
                    {{ question_form.email.errors }}
                </div>

                <!-- Message input -->
                <div data-mdb-input-init class="form-outline">
                    {{ question_form.message }}
                    <label class="form-label" for="message">Повідомлення</label>
                    {{ question_form.message.errors }}
                </div>
                <div style="margin-top: 5px; margin-bottom: 25px">
                    <span>Максимум 500 символів.</span>
                </div>

                <!-- Submit button -->
                <button data-mdb-ripple-init type="submit" class="btn btn-primary btn-block mb-4">Надіслати</button>
            </form>
        </section>
    </section>

{% endblock %}

templates/delivery_info.html
{% extends 'index.html' %}

{% block custom_title %}
    <title>{{ delivery_info.meta_title }}</title>
{% endblock %}

{% block custom_meta %}
    <meta name="description" content="{{ delivery_info.meta_description }}">
    <meta name="robots" content="index, follow">
{% endblock %}

{% block content %}
    <section class="container">
        <div class="row">
            <article class="col col-12 col-lg-5 mt-3">
                {{ delivery_info.delivery_info|safe }}
            </article>
            <article class="col col-12 offset-lg-1 col-lg-6 mt-5 mt-lg-5">
                {{ delivery_info.payments|safe }}
            </article>
        </div>
    </section>

{% endblock %}

templates/return_conditions.html
{% extends 'index.html' %}

{% block custom_title %}
    <title>{{ shipping_info.meta_title }}</title>
{% endblock %}

{% block custom_meta %}
    <meta name="description" content="{{ shipping_info.meta_description }}">
    <meta name="robots" content="index, follow">
{% endblock %}

{% block content %}

    <article class="container mt-3">
        {{ shipping_info.main_info|safe }}
    </article>


{% endblock %}